# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neural Network Building Blocks
email: grady@gradysimon.com
description: > # this means to ignore newlines until "baseurl:"
  A reference guide to the various components that can go into
  neural networks. This guide gives a sense of what these
  components are for and how they work.
baseurl: "/neural-network-building-blocks" # the subpath of your site, e.g. /blog
url: "http://gradysimon.github.io/" # the base hostname & protocol for your site
twitter_username: GradySimon
github_username:  GradySimon

# Build settings
markdown: kramdown
